name: flutter_lotte_cinema_clone
description: Dotte - A Lotte Cinema Clone app.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  logger: ^1.0.0
  shared_preferences: ^2.0.9
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  the_movie_db_client:
    path: ./packages/the_movie_db_client
  dotte_repository:
    path: ./packages/dotte_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  flutter_gen: ^4.1.5
  mocktail: ^0.0.1-dev.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - fonts/

flutter_intl:
  enabled: true
